django_admin_sample/django_admin_sample/urls.py
from django.contrib import admin
from django.urls import path, include

#디렉토리 맵핑
urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('hello_app.urls')),
]

django_admin_sample/hello_app/urls.py
from django.urls import path
from . import views

app_name = 'hello_app'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailsView.as_view(), name='detail'),
    path('<int:pk>/result/', views.ResultView.as_view(), name='results'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

django_admin_sample/hello_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

#model 은 DB를 만드는 개념
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

django_admin_sample/hello_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from hello_app.models import Question, Choice
from django.views.generic import ListView, DetailView

# Create your views here.
# MTV : Model - template - view
# java의 MVC와 같은 개념

#IndexView
class IndexView(ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

#DetailView
class DetailsView(DetailView):
    model = Question
    template_name = 'polls/detail.html'

#vote
def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'You didn`t select a choice',
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('hello_app:results', args=(question.id,)))

#Reuslt views
class ResultView(DetailView):
    model = Question
    template_name = 'polls/results.html'

django_admin_sample/hello_app/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'hello_app:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
{% endfor %}
<input type="submit" value="vote"/>
</form>

django_admin_sample/hello_app/templates/polls/index.html
{%  if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'hello_app:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django_admin_sample/hello_app/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'hello_app:detail' question.id %}">Vote Again?</a>