instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('member/', include('member.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

instagram/post/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    # post
    path('', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:post_pk>/like-toggle/', views.post_like_toggle, name='post_like_toggle'),

    # Comment
    path('<int:post_pk>/comment/create/', views.comment_create, name='comment_create'),
]

instagram/post/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='post')

    def __str__(self):
        return f'Post (PK: {self.pk}, Author: {self.author.username})'

    class Meta:
        ordering = ['-pk']

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()

    def __str__(self):
        return f'Comment (PK: {self.pk}, Author: {self.author.username})'

instagram/post/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'photo',
        )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'content',
        )
        widgets = {
            'content': forms.TextInput(
                attrs={
                    'class': 'content',
                    'placeholder': '댓글 달기...',
                }
            )
        }

    def clean_content(self):
        data = self.cleaned_data['content']
        errors = []
        if data == '':
            errors.append(forms.ValidationError('댓글 내용을 입력해주세요'))
        elif len(data) > 50:
            errors.append(forms.ValidationError('댓글 내용은 50자 이하로 입력해주세요'))
        if errors:
            raise forms.ValidationError(errors)
        return data

instagram/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Post, Comment
from .forms import CommentForm, PostForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from utils.decorators import login_required

# Create your views here.
def post_list(request):
    posts = Post.objects.all()
    context = {
        'posts' : posts,
    }
    return render(request, 'post/post_list.html', context)

@login_required
def comment_create(request, post_pk):
    # GET 파라미터로 전달된 작업 완료 후 이동할 URL값
    next_path = request.GET.get('next')

    # 요청 메서드가 POST방식 일 때만 처리
    if request.method == 'POST':
        # Post인스턴스를 가져오거나 404 Response를 돌려줌
        post = get_object_or_404(Post, pk=post_pk)
        # request.POST데이터를 이용한 Bounded Form생성
        comment_form = CommentForm(request.POST)
        # 올바른 데이터가 Form인스턴스에 바인딩 되어있는지 유효성 검사
        if comment_form.is_valid():
            # 유효성 검사에 통과하면 ModelForm의 save()호출로 인스턴스 생성
            # DB에 저장하지 않고 인스턴스만 생성하기 위해 commit=False옵션 지정
            comment = comment_form.save(commit=False)
            # CommentForm에 지정되지 않았으나 필수요소인 author와 post속성을 지정
            comment.post = post
            comment.author = request.user
            # DB에 저장
            comment.save()

            # 성공 메시지를 다음 request의 결과로 전달하도록 지정
            messages.success(request, '댓글이 등록되었습니다')
        else:
            # 유효성 검사에 실패한 경우
            # 에러 목록을 순회하며 에러메시지를 작성, messages의 error레벨로 추가
            error_msg = '댓글 등록에 실패했습니다\n{}'.format(
                '\n'.join(
                    [f'- {error}'
                     for key, value in comment_form.errors.items()
                     for error in value]))
            messages.error(request, error_msg)

        # next paramater에 값이 담겨 온 경우, 해당 경로로 이동
        if next_path:
            return redirect(next_path)
        # next paramater가 빈 경우 post_list뷰로 이동
        return redirect('post:post_list')

def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    comment_form = CommentForm()
    context = {
        'post':post,
        'comment_form':comment_form,
    }
    return render(request, 'post/post_detail.html',context)

@login_required
def post_create(request):
    if request.method == 'POST':
        # PostForm은 파일을 처리하므로 request.FILES도 함께 바인딩
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            # author 필드를 채우기 위해 인스턴스만 생성
            post = post_form.save(commit=False)
            # author 필드를 채운 후 DB에 저장
            post.author = request.user
            post.save()

            # 성공 알림을 messages에 추가 후 post_list뷰로 이동
            messages.success(request, '사진이 등록되었습니다.')
            return redirect('post:post_list')
    else:
        post_form = PostForm()

    context = {
        'post_form':post_form,
    }
    return render(request, 'post/post_create.html', context)

# POST요청에 대해 커스터마이징한 login_required를 사용한다
@login_required
def post_like_toggle(request, post_pk):
    # GET파라미터로 전달된 이동할 URL
    next_path = request.GET.get('next')
    # post_pk에 해당하는 Post객체
    post = get_object_or_404(Post, pk=post_pk)
    # 요청한 사용자
    user = request.user

    # 사용자의 like_posts목록에서 like_toggle할 Post가 있는지 확인
    filtered_like_posts = user.like_posts.filter(pk=post.pk)
    # 존재할경우, like_posts목록에서 해당 Post를 삭제
    if filtered_like_posts.exists():
        user.like_posts.remove(post)
    # 없을 경우, like_posts목록에 해당 Post를 추가
    else:
        user.like_posts.add(post)

    # 이동할 path가 존재할 경우 해당 위치로, 없을 경우 Post상세페이지로 이동
    if next_path:
        return redirect(next_path)
    return redirect('post:post_detail', post_pk=post_pk)

instagram/templates/include/form.html
<form action="" method="post"{% if enctype == 'file' %} enctype="multipart/form-data"{% endif %}>
	{% csrf_token %}
	{% for field in form %}
		<div class="form-group{% if field.errors %} has-error{% endif %}">
			{{ field.label_tag }}
			{{ field }}
			{% if field.errors %}
				{% for error in field.errors %}
				<span class="help-block">{{ error }}</span>
				{% endfor %}
			{% endif %}
		</div>
	{% endfor %}

	{% if form.non_field_errors %}
		{% for error in login_form.non_field_errors %}
		<p class="text-danger"><b>{{ error }}</b></p>
		{% endfor %}
	{% endif %}
	<button class="btn btn-primary btn-block">{{ submit_title }}</button>
</form>

instagram/templates/include/post.html
<div class="panel panel-default post-item">
	{% if post_type == 'list' %}
	<a href="{% url 'post:post_detail' post_pk=post.pk %}">
		<img src="{{ post.photo.url }}" alt="" class="post-image">
	</a>
	{% else %}
		<img src="{{ post.photo.url }}" alt="" class="post-image">
	{% endif %}
	<div class="panel-body">
		{% if post.comments.exists %}
		<ul class="comment-list">
			{% for comment in post.comments.all %}
			<li class="comment">
				<span class="comment-author">{{ comment.author }}</span>
				<span class="comment-content">{{ comment.content }}</span>
			</li>
			{% endfor %}
		</ul>
		<hr>
		{% endif %}
		<form
			action="{% url 'post:comment_create' post_pk=post.pk %}?next=
			{% if post_type == 'list' %}
				{% url 'post:post_list' %}#post-{{ post.pk }}
			{% elif post_type == 'detail' %}
				{% url 'post:post_detail' post_pk=post.pk %}
			{% endif %}"
			method="POST"
			class="comment-form">
			{% csrf_token %}
			{{ comment_form.content }}
		</form>
	</div>
</div>