instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('member/', include('member.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

instagram/member/urls.py
from django.urls import path
from . import views

app_name = "member"
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

instagram/post/urls.py
from django.urls import path
from . import views

app_name = "post"
urlpatterns = [
    # post
    path('', views.post_list, name='post_list'),
    path('create/', views.post_create, name='post_create'),
    path('<int:post_pk>/', views.post_detail, name='post_detail'),
    path('<int:post_pk>/like-toggle/', views.post_like_toggle, name='post_like_toggle'),

    # Comment
    path('<int:post_pk>/comment/create/', views.comment_create, name='comment_create'),
]

instagram/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<title>Instagram</title>
</head>
<body>
  <!-- <body>태그 바로 밑에 추가 -->
<nav class="top-nav navbar navbar-static-top navbar-default">
	<div class="container">
		<div class="navbar-header">
			<a href="{% url 'post:post_list' %}" class="navbar-brand">Instagram</a>
		</div>

		<div class="collapse navbar-collapse">
			<form action="" class="navbar-form navbar-left search-hashtag-form" role="search">
				<div class="form-group">
					<input type="text" class="form-control search-hashtag-input" placeholder="해시태그 검색...">
				</div>
			</form>
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
				<li><a href="{% url 'post:post_create' %}">+ Add post</a></li>
				<li><a href="">Likes</a></li>
				<li><a href="">Profile</a></li>
				<li><a href="{% url 'member:logout' %}">Logout</a></li>
				{% else %}
				<li><a href="{% url 'member:login' %}">Login</a></li>
				<li><a href="{% url 'member:signup' %}">Signup</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</nav>
<div class="container">
		{% if messages %}
			{% for message in messages %}
				<div class="alert-message alert
					{% if message.tags == 'info' %}
						alert-info
					{% elif message.tags == 'success' %}
						alert-success
					{% elif message.tags == 'warning' %}
						alert-warning
					{% elif message.tags == 'error' %}
						alert-danger
					{% endif %}
					">{{ message }}</div>
			{% endfor %}
		{% endif %}

		<h1>{% block title %}{% endblock %}</h1>

		{% block content %}

		{% endblock %}
	</div>
</body>
</html>